spring:
  application:
    name: config
#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
env:
   test66666
girl:
  name: wangli
  age: 20
